# Data Processes Assignment 2

EIT Digital Data Science: \
Davis Siemens \
Inés Simón del Collado \
Xiya Sun

In [61]:
# libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [62]:
# Reading files
hospital1 = pd.read_excel('./hospital1.xlsx', index_col=None)
hospital2 = pd.read_excel('./hospital2.xlsx', index_col=None)

In [63]:
# Display the first few rows of each dataframe to confirm they were read correctly
hospital1.head()

,patient ID,patient ID.1,nationality,age,gender K=female E=male,date_of_first_symptoms,BASVURUTARIHI,fever_temperature,oxygen_saturation,history_of_fever,...,chronic_hematologic_disease,AIDS_HIV,diabetes_mellitus_type_1,diabetes_mellitus_type_2,rheumatologic_disorder,dementia,tuberculosis,smoking,other_risks,PCR_result
0,11850006,11850006,T.C.,47,K,2022-01-01,2022-01-01,38.2,96.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
1,4373630,4373630,T.C.,23,K,2022-01-01,2022-01-01,37.0,96.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
2,12172023,12172023,T.C.,26,K,2022-01-01,2022-01-01,38.0,95.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
3,72856168,72856168,T.C.,60,K,2022-01-01,2022-01-01,36.5,95.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
4,72200559,72200559,T.C.,72,K,2021-12-22,2021-12-22,36.9,96.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive

In [64]:
hospital2.head()

,patient_id,admission_id,country_of_residence,age,sex,date_of_first_symptoms,admission_date,fever_temperature,oxygen_saturation,history_of_fever,...,chronic_hematologic_disease,AIDS_HIV,diabetes_mellitus_type_1,diabetes_mellitus_type_2,rheumatologic_disorder,dementia,tuberculosis,smoking,other_risks,PCR_result
0,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,NaN
1,88567155.0,45.0,T.C.,52.0,E=male K=female,2021-03-01 00:00:00,2021-03-01 00:00:00,37.3,-1.0,0.0,...,0,0,0,0,0,0,0,0,0,positive
2,36069621.0,181.0,T.C.,47.0,K,2021-03-01 08:38:00,2021-03-01 08:38:00,38.0,95.0,1.0,...,0,0,0,0,0,0,0,0,0,positive
3,57644199.0,36.0,T.C.,36.0,K,2021-03-01 08:39:00,2021-03-01 08:39:00,37.5,88.0,0.0,...,0,0,0,0,0,0,0,0,0,positive
4,81365404.0,32.0,T.C.,30.0,E,2021-03-01 09:25:00,2021-03-01 09:25:00,37.8,87.0,1.0,...,0,0,0,0,0,0,0,0,0,positive

In [65]:
hospital1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14712 entries, 0 to 14711
Data columns (total 54 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   patient ID                       14712 non-null  int64
 1   patient ID.1                     14712 non-null  int64
 2   nationality                      14712 non-null  object
 3   age                              14712 non-null  int64
 4   gender K=female E=male           14712 non-null  object
 5   date_of_first_symptoms           14712 non-null  datetime64[ns]
 6   BASVURUTARIHI                    14712 non-null  datetime64[ns]
 7   fever_temperature                14244 non-null  float64
 8   oxygen_saturation                14708 non-null  float64
 9   history_of_fever                 14712 non-null  int64
 10  cough                            14712 non-null  int64
 11  sore_throat                      14712 non-null  int64
 12  runny_nose                       14712 non-null  int64
 13  wheezing                         14712 non-null  int64
 14  shortness_of_breath              14712 non-null  int64
 15  lower_chest_wall_indrawing       14712 non-null  int64
 16  chest_pain                       14712 non-null  int64
 17  conjunctivitis                   14712 non-null  int64
 18  lymphadenopathy                  14712 non-null  int64
 19  headache                         14712 non-null  int64
 20  loss_of_smell                    14712 non-null  int64
 21  loss_of_taste                    14712 non-null  int64
 22  fatigue_malaise                  14712 non-null  int64
 23  anorexia                         14712 non-null  int64
 24  altered_consciousness_confusion  14712 non-null  int64
 25  muscle_aches                     14712 non-null  int64
 26  joint_pain                       14712 non-null  int64
 27  inability_to_walk                14712 non-null  int64
 28  abdominal_pain                   14712 non-null  int64
 29  diarrhoea                        14712 non-null  int64
 30  vomiting_nausea                  14712 non-null  int64
 31  skin_rash                        14712 non-null  int64
 32  bleeding                         14712 non-null  int64
 33  other_symptoms                   14712 non-null  int64
 34  chronic_cardiac_disease          14712 non-null  int64
 35  hypertension                     14712 non-null  int64
 36  chronic_pulmonary_disease        14712 non-null  int64
 37  asthma                           14712 non-null  int64
 38  chronic_kidney_disease           14705 non-null  float64
 39  obesity                          14690 non-null  float64
 40  liver_disease                    14706 non-null  float64
 41  asplenia                         14690 non-null  float64
 42  chronic_neurological_disorder    14710 non-null  float64
 43  malignant_neoplasm               14712 non-null  int64
 44  chronic_hematologic_disease      14710 non-null  float64
 45  AIDS_HIV                         14710 non-null  float64
 46  diabetes_mellitus_type_1         14709 non-null  float64
 47  diabetes_mellitus_type_2         14710 non-null  float64
 48  rheumatologic_disorder           14710 non-null  float64
 49  dementia                         14710 non-null  float64
 50  tuberculosis                     14712 non-null  int64
 51  smoking                          14712 non-null  int64
 52  other_risks                      14712 non-null  int64
 53  PCR_result                       13536 non-null  object
dtypes: datetime64[ns](2), float64(13), int64(36), object(3)
memory usage: 6.1+ MB

In [66]:
# lets see if both dates have the same value for each row
mismatched_rows = hospital1[hospital1['date_of_first_symptoms'] != hospital1['BASVURUTARIHI']]
mismatched_rows #since we have the same values, we can drop one column

Empty DataFrame
Columns: [patient ID, patient ID.1, nationality, age, gender K=female E=male, date_of_first_symptoms, BASVURUTARIHI, fever_temperature, oxygen_saturation, history_of_fever, cough, sore_throat, runny_nose, wheezing, shortness_of_breath, lower_chest_wall_indrawing, chest_pain, conjunctivitis, lymphadenopathy, headache, loss_of_smell, loss_of_taste, fatigue_malaise, anorexia, altered_consciousness_confusion, muscle_aches, joint_pain, inability_to_walk, abdominal_pain, diarrhoea, vomiting_nausea, skin_rash, bleeding, other_symptoms, chronic_cardiac_disease, hypertension, chronic_pulmonary_disease, asthma, chronic_kidney_disease, obesity, liver_disease, asplenia, chronic_neurological_disorder, malignant_neoplasm, chronic_hematologic_disease, AIDS_HIV, diabetes_mellitus_type_1, diabetes_mellitus_type_2, rheumatologic_disorder, dementia, tuberculosis, smoking, other_risks, PCR_result]
Index: []

[0 rows x 54 columns]

In [67]:
# we drop the column BASVURUTARIHI and we only keep the date of the date_of_symp
hospital1.drop(['BASVURUTARIHI'], axis=1, inplace=True)
hospital1['date_of_first_symptoms'] = hospital1['date_of_first_symptoms'].dt.date
hospital1.head()

,patient ID,patient ID.1,nationality,age,gender K=female E=male,date_of_first_symptoms,fever_temperature,oxygen_saturation,history_of_fever,cough,...,chronic_hematologic_disease,AIDS_HIV,diabetes_mellitus_type_1,diabetes_mellitus_type_2,rheumatologic_disorder,dementia,tuberculosis,smoking,other_risks,PCR_result
0,11850006,11850006,T.C.,47,K,2022-01-01,38.2,96.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
1,4373630,4373630,T.C.,23,K,2022-01-01,37.0,96.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
2,12172023,12172023,T.C.,26,K,2022-01-01,38.0,95.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
3,72856168,72856168,T.C.,60,K,2022-01-01,36.5,95.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive
4,72200559,72200559,T.C.,72,K,2021-12-22,36.9,96.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,positive

In [68]:
hospital2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12737 entries, 0 to 12736
Data columns (total 54 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   patient_id                       12734 non-null  float64
 1   admission_id                     12734 non-null  float64
 2   country_of_residence             12734 non-null  object
 3   age                              12734 non-null  float64
 4   sex                              12734 non-null  object
 5   date_of_first_symptoms           12734 non-null  datetime64[ns]
 6   admission_date                   12734 non-null  datetime64[ns]
 7   fever_temperature                11515 non-null  float64
 8   oxygen_saturation                12730 non-null  float64
 9   history_of_fever                 12729 non-null  float64
 10  cough                            12736 non-null  float64
 11  sore_throat                      12736 non-null  float64
 12  runny_nose                       12734 non-null  float64
 13  wheezing                         12734 non-null  float64
 14  shortness_of_breath              12734 non-null  float64
 15  lower_chest_wall_indrawing       12734 non-null  float64
 16  chest_pain                       12734 non-null  float64
 17  conjunctivitis                   12734 non-null  float64
 18  lymphadenopathy                  12734 non-null  float64
 19  headache                         12736 non-null  float64
 20  loss_of_smell                    12736 non-null  float64
 21  loss_of_taste                    12736 non-null  float64
 22  fatigue_malaise                  12736 non-null  float64
 23  anorexia                         12736 non-null  float64
 24  altered_consciousness_confusion  12736 non-null  float64
 25  muscle_aches                     12736 non-null  float64
 26  joint_pain                       12736 non-null  float64
 27  inability_to_walk                12736 non-null  float64
 28  abdominal_pain                   12736 non-null  float64
 29  diarrhoea                        12736 non-null  float64
 30  vomiting_nausea                  12736 non-null  float64
 31  skin_rash                        12736 non-null  float64
 32  bleeding                         12698 non-null  float64
 33  other_symptoms                   12698 non-null  float64
 34  chronic_cardiac_disease          12736 non-null  float64
 35  hypertension                     12736 non-null  float64
 36  chronic_pulmonary_disease        12736 non-null  float64
 37  asthma                           12736 non-null  float64
 38  chronic_kidney_disease           12736 non-null  float64
 39  obesity                          12737 non-null  int64
 40  liver_disease                    12737 non-null  int64
 41  asplenia                         12737 non-null  int64
 42  chronic_neurological_disorder    12737 non-null  int64
 43  malignant_neoplasm               12737 non-null  int64
 44  chronic_hematologic_disease      12737 non-null  int64
 45  AIDS_HIV                         12737 non-null  int64
 46  diabetes_mellitus_type_1         12737 non-null  int64
 47  diabetes_mellitus_type_2         12737 non-null  int64
 48  rheumatologic_disorder           12737 non-null  int64
 49  dementia                         12737 non-null  int64
 50  tuberculosis                     12737 non-null  int64
 51  smoking                          12737 non-null  int64
 52  other_risks                      12737 non-null  int64
 53  PCR_result                       12703 non-null  object
dtypes: datetime64[ns](2), float64(35), int64(14), object(3)
memory usage: 5.2+ MB

In [69]:
# lets see if both dates have the same value for each row
mismatched_rows = hospital2[hospital2['date_of_first_symptoms'] != hospital2['admission_date']]
mismatched_rows #since we have the same values, we can drop one column

,patient_id,admission_id,country_of_residence,age,sex,date_of_first_symptoms,admission_date,fever_temperature,oxygen_saturation,history_of_fever,...,chronic_hematologic_disease,AIDS_HIV,diabetes_mellitus_type_1,diabetes_mellitus_type_2,rheumatologic_disorder,dementia,tuberculosis,smoking,other_risks,PCR_result
0,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,NaN
12735,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,positive
12736,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,positive

In [70]:
# we drop the column BASVURUTARIHI and we only keep the date of the date_of_symp
hospital2.drop(['admission_date'], axis=1, inplace=True)
hospital2['date_of_first_symptoms'] = hospital2['date_of_first_symptoms'].dt.date
hospital2.head()

,patient_id,admission_id,country_of_residence,age,sex,date_of_first_symptoms,fever_temperature,oxygen_saturation,history_of_fever,cough,...,chronic_hematologic_disease,AIDS_HIV,diabetes_mellitus_type_1,diabetes_mellitus_type_2,rheumatologic_disorder,dementia,tuberculosis,smoking,other_risks,PCR_result
0,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,NaN
1,88567155.0,45.0,T.C.,52.0,E=male K=female,2021-03-01,37.3,-1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,positive
2,36069621.0,181.0,T.C.,47.0,K,2021-03-01,38.0,95.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,positive
3,57644199.0,36.0,T.C.,36.0,K,2021-03-01,37.5,88.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,positive
4,81365404.0,32.0,T.C.,30.0,E,2021-03-01,37.8,87.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,positive

In [71]:
# we make the names of the columns in the same format
hospital1.columns = hospital1.columns.str.lower().str.replace(' ', '_')
hospital2.columns = hospital2.columns.str.lower().str.replace(' ', '_')

# let's see if both dataframes have the same column names 
columns_hospital1 = set(hospital1.columns)
columns_hospital2 = set(hospital2.columns)
comparison_df = pd.DataFrame({
    'Column': list(columns_hospital1.union(columns_hospital2)),
    'In_Hospital1': [col in columns_hospital1 for col in columns_hospital1.union(columns_hospital2)],
    'In_Hospital2': [col in columns_hospital2 for col in columns_hospital1.union(columns_hospital2)]
})

# let's see which columns are different
comparison_df[comparison_df['In_Hospital1'] != comparison_df['In_Hospital2']]

                    Column  In_Hospital1  In_Hospital2
4              nationality          True         False
9     country_of_residence         False          True
11            patient_id.1          True         False
22            admission_id         False          True
37  gender_k=female_e=male          True         False
52                     sex         False          True

In [72]:
# observing these columns, we can notice that gender=sex and country=nationality. 
# we keep the patient_id and admission_id
rename_hospital1 = {'nationality': 'country',
                    'gender_k=female_e=male': 'gender'}
rename_hospital2 = {'country_of_residence': 'country',
                    'sex': 'gender'}

hospital1.rename(columns=rename_hospital1, inplace=True)
hospital2.rename(columns=rename_hospital2, inplace=True)

In [73]:
# before merging, we make sure that all the types from both datasets are the same (it doesn't work well the upcasting that turns everything to object)
dtypes_hospital1 = hospital1.dtypes
dtypes_hospital2 = hospital2.dtypes

# Create a DataFrame to compare
dtype_comparison = pd.DataFrame({
    'Column': sorted(set(hospital1.columns).union(set(hospital2.columns))),
    'Hospital1_Dtype': [dtypes_hospital1[col] if col in hospital1.columns else None for col in sorted(set(hospital1.columns).union(set(hospital2.columns)))],
    'Hospital2_Dtype': [dtypes_hospital2[col] if col in hospital2.columns else None for col in sorted(set(hospital1.columns).union(set(hospital2.columns)))]
})

# Add a column to indicate if the dtypes are the same
dtype_comparison['Same_Dtype'] = dtype_comparison['Hospital1_Dtype'] == dtype_comparison['Hospital2_Dtype']
dtype_comparison

,Column,Hospital1_Dtype,Hospital2_Dtype,Same_Dtype
0,abdominal_pain,int64,float64,False
1,admission_id,None,float64,False
2,age,int64,float64,False
3,aids_hiv,float64,int64,False
4,altered_consciousness_confusion,int64,float64,False
5,anorexia,int64,float64,False
6,asplenia,float64,int64,False
7,asthma,int64,float64,False
8,bleeding,int64,float64,False
9,chest_pain,int64,float64,False
10,chronic_cardiac_disease,int64,float64,False
11,chronic_hematologic_disease,float64,int64,False
12,chronic_kidney_disease,float64,float64,True
13,chronic_neurological_disorder,float64,int64,False
14,chronic_pulmonary_disease,int64,float64,False
15,conjunctivitis,int64,float64,False
16,cough,int64,float64,False
17,country,object,object,True
18,date_of_first_symptoms,object,object,True
19,dementia,float64,int64,False
20,diabetes_mellitus_type_1,float64,int64,False
21,diabetes_mellitus_type_2,float64,int64,False
22,diarrhoea,int64,float64,False
23,fatigue_malaise,int64,float64,False
24,fever_temperature,float64,float64,True
25,gender,object,object,True
26,headache,int64,float64,False
27,history_of_fever,int64,float64,False
28,hypertension,int64,float64,False
29,inability_to_walk,int64,float64,False
30,joint_pain,int64,float64,False
31,liver_disease,float64,int64,False
32,loss_of_smell,int64,float64,False
33,loss_of_taste,int64,float64,False
34,lower_chest_wall_indrawing,int64,float64,False
35,lymphadenopathy,int64,float64,False
36,malignant_neoplasm,int64,int64,True
37,muscle_aches,int64,float64,False
38,obesity,float64,int64,False
39,other_risks,int64,int64,True
40,other_symptoms,int64,float64,False
41,oxygen_saturation,float64,float64,True
42,patient_id,int64,float64,False
43,patient_id.1,int64,None,False
44,pcr_result,object,object,True
45,rheumatologic_disorder,float64,int64,False
46,runny_nose,int64,float64,False
47,shortness_of_breath,int64,float64,False
48,skin_rash,int64,float64,False
49,smoking,int64,int64,True
50,sore_throat,int64,float64,False
51,tuberculosis,int64,int64,True
52,vomiting_nausea,int64,float64,False
53,wheezing,int64,float64,False

In [82]:
# for the upcasting when we have int and float we should make it float. But in our situation, the floats does not make sense, e.g age or binary cases. 
# therefore, in variables that we have int means that it is enough, so we make it int 
# the only variable that makes sense to be float is temperature, that is already in both
for column in hospital1.columns.intersection(hospital2.columns):
    if dtypes_hospital1[column] != dtypes_hospital2[column]:
        #hospital1[column] = pd.to_numeric(hospital1[column], downcast='integer', errors='coerce')
        #hospital2[column] = pd.to_numeric(hospital2[column], downcast='integer', errors='coerce')
        hospital1[column] = hospital1[column].astype('Int64')
        hospital2[column] = hospital2[column].astype('Int64')

In [83]:
hospital2.dtypes

patient_id                           Int64
admission_id                       float64
country                             object
age                                  Int64
gender                              object
date_of_first_symptoms              object
fever_temperature                  float64
oxygen_saturation                  float64
history_of_fever                     Int64
cough                                Int64
sore_throat                          Int64
runny_nose                           Int64
wheezing                             Int64
shortness_of_breath                  Int64
lower_chest_wall_indrawing           Int64
chest_pain                           Int64
conjunctivitis                       Int64
lymphadenopathy                      Int64
headache                             Int64
loss_of_smell                        Int64
loss_of_taste                        Int64
fatigue_malaise                      Int64
anorexia                             Int64
altered_consciousness_confusion      Int64
muscle_aches                         Int64
joint_pain                           Int64
inability_to_walk                    Int64
abdominal_pain                       Int64
diarrhoea                            Int64
vomiting_nausea                      Int64
skin_rash                            Int64
bleeding                             Int64
other_symptoms                       Int64
chronic_cardiac_disease              Int64
hypertension                         Int64
chronic_pulmonary_disease            Int64
asthma                               Int64
chronic_kidney_disease             float64
obesity                              Int64
liver_disease                        Int64
asplenia                             Int64
chronic_neurological_disorder        Int64
malignant_neoplasm                   int64
chronic_hematologic_disease          Int64
aids_hiv                             Int64
diabetes_mellitus_type_1             Int64
diabetes_mellitus_type_2             Int64
rheumatologic_disorder               Int64
dementia                             Int64
tuberculosis                         int64
smoking                              int64
other_risks                          int64
pcr_result                          object
dtype: object

In [84]:
#make sure if are the same now
dtypes_hospital1 = hospital1.dtypes
dtypes_hospital2 = hospital2.dtypes

dtype_comparison = pd.DataFrame({
    'Column': sorted(set(hospital1.columns).union(set(hospital2.columns))),
    'Hospital1_Dtype': [dtypes_hospital1[col] if col in hospital1.columns else None for col in sorted(set(hospital1.columns).union(set(hospital2.columns)))],
    'Hospital2_Dtype': [dtypes_hospital2[col] if col in hospital2.columns else None for col in sorted(set(hospital1.columns).union(set(hospital2.columns)))]
})

dtype_comparison['Same_Dtype'] = dtype_comparison['Hospital1_Dtype'] == dtype_comparison['Hospital2_Dtype']
dtype_comparison

,Column,Hospital1_Dtype,Hospital2_Dtype,Same_Dtype
0,abdominal_pain,Int64,Int64,True
1,admission_id,None,float64,False
2,age,Int64,Int64,True
3,aids_hiv,Int64,Int64,True
4,altered_consciousness_confusion,Int64,Int64,True
5,anorexia,Int64,Int64,True
6,asplenia,Int64,Int64,True
7,asthma,Int64,Int64,True
8,bleeding,Int64,Int64,True
9,chest_pain,Int64,Int64,True
10,chronic_cardiac_disease,Int64,Int64,True
11,chronic_hematologic_disease,Int64,Int64,True
12,chronic_kidney_disease,float64,float64,True
13,chronic_neurological_disorder,Int64,Int64,True
14,chronic_pulmonary_disease,Int64,Int64,True
15,conjunctivitis,Int64,Int64,True
16,cough,Int64,Int64,True
17,country,object,object,True
18,date_of_first_symptoms,object,object,True
19,dementia,Int64,Int64,True
20,diabetes_mellitus_type_1,Int64,Int64,True
21,diabetes_mellitus_type_2,Int64,Int64,True
22,diarrhoea,Int64,Int64,True
23,fatigue_malaise,Int64,Int64,True
24,fever_temperature,float64,float64,True
25,gender,object,object,True
26,headache,Int64,Int64,True
27,history_of_fever,Int64,Int64,True
28,hypertension,Int64,Int64,True
29,inability_to_walk,Int64,Int64,True
30,joint_pain,Int64,Int64,True
31,liver_disease,Int64,Int64,True
32,loss_of_smell,Int64,Int64,True
33,loss_of_taste,Int64,Int64,True
34,lower_chest_wall_indrawing,Int64,Int64,True
35,lymphadenopathy,Int64,Int64,True
36,malignant_neoplasm,int64,int64,True
37,muscle_aches,Int64,Int64,True
38,obesity,Int64,Int64,True
39,other_risks,int64,int64,True
40,other_symptoms,Int64,Int64,True
41,oxygen_saturation,float64,float64,True
42,patient_id,Int64,Int64,True
43,patient_id.1,int64,None,False
44,pcr_result,object,object,True
45,rheumatologic_disorder,Int64,Int64,True
46,runny_nose,Int64,Int64,True
47,shortness_of_breath,Int64,Int64,True
48,skin_rash,Int64,Int64,True
49,smoking,int64,int64,True
50,sore_throat,Int64,Int64,True
51,tuberculosis,int64,int64,True
52,vomiting_nausea,Int64,Int64,True
53,wheezing,Int64,Int64,True

In [ ]:
# since we do the intersection between doth datasets, the columns that are not in both is going to be excluded directly
common_columns = sorted(set(hospital1.columns).intersection(set(hospital2.columns)))

all_patients = pd.concat([hospital1[common_columns], hospital2[common_columns]], ignore_index=True)
all_patients.drop(['patient_id'], axis=1, inplace=True) #this one is in both 
all_patients.head()

,abdominal_pain,age,aids_hiv,altered_consciousness_confusion,anorexia,asplenia,asthma,bleeding,chest_pain,chronic_cardiac_disease,...,pcr_result,rheumatologic_disorder,runny_nose,shortness_of_breath,skin_rash,smoking,sore_throat,tuberculosis,vomiting_nausea,wheezing
0,0,47,0,0,0,0,0,0,0,0,...,positive,0,0,0,0,0,0,0,0,0
1,0,23,0,0,0,0,0,0,0,0,...,positive,0,0,0,0,0,1,0,0,0
2,0,26,0,0,0,0,0,0,0,0,...,positive,0,0,0,0,0,0,0,0,0
3,0,60,0,0,0,0,0,0,0,0,...,positive,0,0,0,0,0,0,0,0,0
4,0,72,0,0,0,0,0,0,1,0,...,positive,0,0,0,0,0,0,0,0,0

In [90]:
#check the dtypes
all_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27449 entries, 0 to 27448
Data columns (total 51 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   abdominal_pain                   27448 non-null  Int64
 1   age                              27446 non-null  Int64
 2   aids_hiv                         27447 non-null  Int64
 3   altered_consciousness_confusion  27448 non-null  Int64
 4   anorexia                         27448 non-null  Int64
 5   asplenia                         27427 non-null  Int64
 6   asthma                           27448 non-null  Int64
 7   bleeding                         27410 non-null  Int64
 8   chest_pain                       27446 non-null  Int64
 9   chronic_cardiac_disease          27448 non-null  Int64
 10  chronic_hematologic_disease      27447 non-null  Int64
 11  chronic_kidney_disease           27441 non-null  float64
 12  chronic_neurological_disorder    27447 non-null  Int64
 13  chronic_pulmonary_disease        27448 non-null  Int64
 14  conjunctivitis                   27446 non-null  Int64
 15  cough                            27448 non-null  Int64
 16  country                          27446 non-null  object
 17  date_of_first_symptoms           27446 non-null  object
 18  dementia                         27447 non-null  Int64
 19  diabetes_mellitus_type_1         27446 non-null  Int64
 20  diabetes_mellitus_type_2         27447 non-null  Int64
 21  diarrhoea                        27448 non-null  Int64
 22  fatigue_malaise                  27448 non-null  Int64
 23  fever_temperature                25759 non-null  float64
 24  gender                           27446 non-null  object
 25  headache                         27448 non-null  Int64
 26  history_of_fever                 27441 non-null  Int64
 27  hypertension                     27448 non-null  Int64
 28  inability_to_walk                27448 non-null  Int64
 29  joint_pain                       27448 non-null  Int64
 30  liver_disease                    27443 non-null  Int64
 31  loss_of_smell                    27448 non-null  Int64
 32  loss_of_taste                    27448 non-null  Int64
 33  lower_chest_wall_indrawing       27446 non-null  Int64
 34  lymphadenopathy                  27446 non-null  Int64
 35  malignant_neoplasm               27449 non-null  int64
 36  muscle_aches                     27448 non-null  Int64
 37  obesity                          27427 non-null  Int64
 38  other_risks                      27449 non-null  int64
 39  other_symptoms                   27410 non-null  Int64
 40  oxygen_saturation                27438 non-null  float64
 41  pcr_result                       26239 non-null  object
 42  rheumatologic_disorder           27447 non-null  Int64
 43  runny_nose                       27446 non-null  Int64
 44  shortness_of_breath              27446 non-null  Int64
 45  skin_rash                        27448 non-null  Int64
 46  smoking                          27449 non-null  int64
 47  sore_throat                      27448 non-null  Int64
 48  tuberculosis                     27449 non-null  int64
 49  vomiting_nausea                  27448 non-null  Int64
 50  wheezing                         27446 non-null  Int64
dtypes: Int64(40), float64(3), int64(4), object(4)
memory usage: 11.7+ MB